# name: cfnLiteRoleExample
# resources:
#   role:
#     AssumeRolePolicyDocument:
#       Principal:
#         service: "ec2.amazonaws.com"
#       Action:
#         - "sts:AssumeRole"
#     policies:
#       - Action: "cloudwatch:*"
#       - Action: "lakeformation:*"

Resources:
  cfnLiteRoleExampleROLE:
    Properties:
      AssumeRolePolicyDocument:
        PolicyDocument:
          Statement:
            - Action:
                - sts:AssumeRole
              Effect: Allow
              Principal:
                service: ec2.amazonaws.com
              Resources:
                - '*'
          Version: '2012-10-17'
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - cloudwatch:*
                Effect: Allow
                Resources:
                  - '*'
              - Action:
                  - lakeformation:*
                Effect: Allow
                Resources:
                  - '*'
            Version: '2012-10-17'
          PolicyName: Example cfnlite policy
      RoleName: TestRole
    Type: AWS::IAM::Role
